export interface DetailSOModel{
  header:HeaderDetailSO,
  detail:DataBarangDetailSO[],
  pembayaran:PembayaranDetailSO,
}

export interface HeaderDetailSO {
  idperusahaan: string|null,
  idso: string|null,
  kodeso: string|null,
  kodepo: string|null,
  idlokasi: string|null,
  omnichannel: string|null,
  idcustomer: string|null,
  idmarketing: string|null,
  idsubcustomer: string|null,
  idekspedisi: string|null,
  scanbarcode: string|null,
  alamatkirim: string|null,
  tgltrans: string|null,
  idsyaratbayar: string|null,
  tgljatuhtempo:string|null,
  tglkirim: string|null,
  total: string|null,
  ppnrp: string|null,
  pembulatan: string|null,
  grandtotal: string|null,
  catatan: string|null,
  userapprove: string|null,
  approve: string|null,
  tglapprove: string|null,
  userentry: string|null,
  tglentry: string|null,
  userbatal: string|null,
  tglbatal: string|null,
  alasanbatal: string|null,
  status:string|null,
  closing: string|null,
  kodelokasi: string|null,
  namalokasi: string|null,
  kodecustomer: string|null,
  namacustomer: string|null,
  alamat: string|null,
  kota: string|null,
  propinsi: string|null,
  negara: string|null,
  telp: string|null,
  kodesubcustomer: string|null,
  namasubcustomer: string|null,
  telpsubcustomer: string|null,
  alamatsubcustomer: string|null,
  kotasubcustomer: string|null,
  propinsisubcustomer: string|null,
  negarasubcustomer: string|null,
  userbuat: string|null,
  userhapus:string|null,
  kodeekspedisi:string|null,
  namaekspedisi:string|null,
  maxnota: string|null,
  maxcredit: string|null,
  ceknotajatuhtempo: string|null,
}

export interface DataBarangDetailSO{
  tgltrans: string|null,
  idso: string|null,
  kodeso:string|null,
  idbarang: string|null,
  jml: string|null,
  terpenuhi: string|null,
  sisa: string|null,
  kodebarang: string|null,
  namabarang: string|null,
  satuan: string|null,
  konversi: string|null,
  idcurrency: string|null,
  simbol: string|null,
  harga: string|null,
  discpersen: string|null,
  disc: string|null,
  disckurs: string|null,
  subtotal: string|null,
  nilaikurs: string|null,
  hargakurs: string|null,
  subtotalkurs: string|null,
  pakaippn: string|null,
  ppnpersen: string|null,
  ppnrp:string|null,
  tutup: string|null,
  catatan: string|null,
  idsyaratbayar: string|null,
  namasyaratbayar: string|null,
  barcodesatuan1: string|null,
  partnumber: string|null,
  idmerk: string|null,
  kodemerk: string|null,
  idlokasi: string|null,
  scanbarcodebbk:string|null,
  disccustomermin:string|null,
  disccustomermax: string|null,
  namacustomer: string|null,
  idcustomer: string|null,
  disctipecustomermin:string|null,
  disctipecustomermax: string|null,
  namatipecustomer: string|null,
  discmerkmin: string|null,
  discmerkmax:string|null,
  namamerk: string|null,
  ppn: string|null,
  omnichannel: string|null,
  namabarangalias: string|null,
}

export interface PembayaranDetailSO{
  amount: string|null,
  idalatbayar: string|null,
  namaalatbayar: string|null,
}