export interface TransaksiBeliModel{
  userbuat: string|null,
  userhapus:string|null,
  tgltrans: string|null,
  tgljatuhtempo:string|null,
  idtrans: string|null,
  kodetrans: string|null,
  noinvoicesupplier: string|null,
  idlokasi: string|null,
  idsupplier: string|null,
  idsyaratbayar: string|null,
  tglentry:string|null,
  tglbatal:string|null,
  alasanbatal: string|null,
  total:string|null,
  ppnrp:string|null,
  pph22rp: string|null,
  pembulatan:string|null,
  grandtotal: string|null,
  catatan:string|null,
  status:string|null,
  closing: string|null,
  idbbm:string|null,
  selisih:string|null,
  namasyaratbayar:string|null,
  biayakirim:string|null,
  kodelokasi:string|null,
  namalokasi:string|null,
  kodesupplier: string|null,
  namasupplier:string|null,
  statusBeli:string|null,
  jenistransaksi:string|null,
}