export interface VerifikasiPelunasanModel {
  idperusahaan?: string|null,
  idlokasi?: string|null,
  idpelunasan?: string|null,
  kodepelunasan?: string|null,
  idtandaterima?: string|null,
  idsupplier?: string|null,
  idkas?: string|null,
  idmemo?: string|null,
  tgltrans?: string|null,
  carabayar?: string|null,
  idgiro?: string|null,
  amountbg?:string|null,
  namabank?: string|null,
  tglcairbg?:string|null,
  statusbg?:string|null,
  total?: string|null,
  catatan?: string|null,
  userentry?: string|null,
  tglentry?: string|null,
  userbatal?: string|null,
  tglbatal?: string|null,
  alasanbatal?: string|null,
  status?:string|null,
  closing?: string|null,
}